# Generated by Django 5.2.6 on 2026-01-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pending_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
