# Generated by Django 5.2.6 on 2026-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_currency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_customer_account_type_currency',
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=3),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('customer', 'account_type'), name='unique_customer_account_type'),
        ),
    ]
